server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: chat-bot-service
              uri: lb://CHAT-BOT-SERVICE
              predicates:
                - Path=/chat-bot/**
              filters:
                - StripPrefix=1
            
            - id: company-service
              uri: lb://COMPANY-SERVICE
              predicates:
                - Path=/company/**
              filters:
                - StripPrefix=1
            
            - id: stock-service
              uri: lb://STOCK-SERVICE
              predicates:
                - Path=/stock/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

